from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from aae_pipeline.local_runner import project_fingerprint, project_inventory


class ReproducibilityTests(unittest.TestCase):
    def test_fingerprint_ignores_generated_bytecode(self):
        before = project_fingerprint(ROOT)
        cache = ROOT / "src/aae_pipeline/__pycache__"
        cache.mkdir(exist_ok=True)
        marker = cache / "audit_test.cpython-314.pyc"
        marker.write_bytes(b"generated bytecode must not affect fingerprint")
        try:
            after = project_fingerprint(ROOT)
        finally:
            marker.unlink(missing_ok=True)
        self.assertEqual(before, after)
        self.assertFalse(any("__pycache__" in item["path"] for item in project_inventory(ROOT)))


if __name__ == "__main__":
    unittest.main()
