from __future__ import annotations

import csv
import json
import logging
import shutil
from datetime import date, datetime, time, timezone
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from .acquisition import (
    acquire_resolved_github_source,
    git_blob_sha1_file,
    resolve_github_source,
    verify_pinned_local_source,
)
from .aggregate import aggregate_multi_area
from .controlled_inputs import verify_controlled_inputs
from .geography import GeographyIndex
from .governance import load_governed_versions
from .payloads import build_payloads
from .pipeline import run_build
from .source_prepare import prepare_alarm_source
from .utils import (
    clean_dir,
    ensure_dir,
    file_inventory,
    parse_datetime_utc,
    read_csv_rows,
    read_json,
    sha256_file,
    stable_id,
    utc_now_iso,
    write_csv_rows,
    write_json,
)

LOG = logging.getLogger("aae.local")

NUMERIC_INT_FIELDS = {
    "alarm_seconds", "available_school_seconds", "expected_school_seconds", "affected_school_days",
    "available_school_days", "expected_school_days", "school_time_alarm_episodes", "school_count",
    "learners_total", "learners_offline", "learners_online", "learners_mixed",
}
NUMERIC_FLOAT_FIELDS = {"alarm_hours", "school_time_under_alarm_pct"}


def configure_logging(log_path: Path) -> None:
    ensure_dir(log_path.parent)
    LOG.setLevel(logging.INFO)
    for handler in list(LOG.handlers):
        handler.close()
        LOG.removeHandler(handler)
    formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    stream = logging.StreamHandler()
    stream.setFormatter(formatter)
    file_handler = logging.FileHandler(log_path, encoding="utf-8")
    file_handler.setFormatter(formatter)
    LOG.addHandler(stream)
    LOG.addHandler(file_handler)


def active_school_years(root: Path, assumptions: dict[str, Any]) -> list[str]:
    rows = read_csv_rows(root / assumptions["calendar"]["school_years_file"])
    return [row["school_year"] for row in rows if row.get("is_active", "1") != "0"]


def project_inventory(root: Path) -> list[dict[str, Any]]:
    """Return the deterministic executable/input inventory used for checkpointing.

    Generated bytecode and operating-system metadata are deliberately excluded so the
    same package has the same fingerprint on macOS, Linux, and different Python builds.
    """
    paths: list[Path] = []
    for relative in ["airalarms.py", "run_local.sh", "pyproject.toml", "uv.lock"]:
        path = root / relative
        if path.exists():
            paths.append(path)
    for folder in ["src", "config", "data/reference", "data/assumptions"]:
        base = root / folder
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file():
                continue
            relative_parts = path.relative_to(root).parts
            if "__pycache__" in relative_parts or path.suffix in {".pyc", ".pyo"} or path.name in {".DS_Store"}:
                continue
            paths.append(path)
    return [
        {
            "path": path.relative_to(root).as_posix(),
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        for path in sorted(set(paths))
    ]


def project_fingerprint(root: Path) -> str:
    components = [f"{item['path']}:{item['sha256']}" for item in project_inventory(root)]
    return stable_id(*components, length=32)


def _school_year_coverage_bounds(root: Path, assumptions: dict[str, Any], school_year: str) -> tuple[datetime, datetime]:
    row = next(r for r in read_csv_rows(root / assumptions["calendar"]["school_years_file"]) if r["school_year"] == school_year)
    tz = ZoneInfo(assumptions["timezone"])
    start = datetime.combine(date.fromisoformat(row["start_date"]), time(0, 0), tzinfo=tz).astimezone(timezone.utc)
    end = datetime.combine(date.fromisoformat(row["end_date"]), time(23, 59, 59), tzinfo=tz).astimezone(timezone.utc)
    return start, end


def run_local_build(
    *,
    root: Path,
    output_dir: Path,
    alarm_source: Path | None = None,
    school_years: list[str] | None = None,
    oblast_ids: list[str] | None = None,
    resume: bool = True,
    fresh: bool = False,
    alarm_source_sha256: str | None = None,
    alarm_source_upstream_commit: str | None = None,
    alarm_source_git_blob: str | None = None,
    controlled_input_root: Path | None = None,
    source_cache_dir: Path | None = None,
) -> dict[str, Any]:
    if fresh and output_dir.exists():
        clean_dir(output_dir)
    ensure_dir(output_dir)
    configure_logging(output_dir / "logs/build.log")

    assumptions = read_json(root / "config/assumptions.json")
    sources = read_json(root / "config/sources.json")
    governed_versions = load_governed_versions(root, assumptions)
    verify_controlled_inputs(root, controlled_input_root)
    geography = GeographyIndex(root, sources)
    years = school_years or active_school_years(root, assumptions)
    areas = oblast_ids or sorted(geography.oblast_name_by_id)
    unknown_years = [year for year in years if year not in active_school_years(root, assumptions)]
    unknown_areas = [area for area in areas if area not in geography.oblast_name_by_id]
    if unknown_years or unknown_areas:
        raise ValueError(f"Unknown selections: school_years={unknown_years}, oblast_ids={unknown_areas}")

    prepared_dir = output_dir / "prepared_source"
    batches_dir = ensure_dir(output_dir / "batches")
    final_dir = ensure_dir(output_dir / "final")
    state_dir = ensure_dir(output_dir / "state")
    state_path = state_dir / "build_state.json"
    fingerprint = project_fingerprint(root)
    previous = read_json(state_path) if state_path.exists() else None
    if previous and resume and not fresh and previous.get("status") not in {"RUNNING", "PARTIAL"}:
        raise RuntimeError(
            "A completed build is not resumable. Start a clean build with "
            "'./run_local.sh fresh-build' so the current upstream source is resolved again."
        )

    cache_dir = source_cache_dir or (output_dir.parent / "source-cache")
    source_provenance: dict[str, Any]
    if alarm_source is None:
        resolution = resolve_github_source(sources["air_alarm_source"])
        previous_provenance = previous.get("source_provenance", {}) if previous else {}
        can_resume_immutable = (
            previous is not None
            and resume
            and not fresh
            and previous.get("status") in {"RUNNING", "PARTIAL"}
            and previous.get("project_fingerprint") == fingerprint
            and previous_provenance.get("resolved_upstream_commit_sha")
            == resolution["resolved_upstream_commit_sha"]
            and previous_provenance.get("upstream_git_blob_sha1")
            == resolution["upstream_git_blob_sha1"]
            and previous.get("source_sha256")
        )
        cached = cache_dir / "sha256" / f"{previous.get('source_sha256')}.csv" if can_resume_immutable else None
        if cached and cached.is_file():
            if (
                cached.stat().st_size != resolution["expected_resolved_byte_size"]
                or sha256_file(cached) != previous["source_sha256"]
                or git_blob_sha1_file(cached) != resolution["upstream_git_blob_sha1"]
            ):
                raise RuntimeError("Cached immutable source failed resume identity verification")
            alarm_source = cached
            source_provenance = {
                **previous_provenance,
                "source_mode": "resumed_immutable_source",
                "resolved_at_utc": resolution["resolved_at_utc"],
                "resumed_at_utc": utc_now_iso(),
            }
            LOG.info("Source mode: resumed immutable source")
        else:
            alarm_source, source_provenance = acquire_resolved_github_source(resolution, cache_dir)
            LOG.info("Source mode: live resolved source")
    else:
        alarm_source = alarm_source.resolve()
        source_provenance = verify_pinned_local_source(
            alarm_source,
            expected_sha256=alarm_source_sha256 or "",
            upstream_commit_sha=alarm_source_upstream_commit,
            upstream_git_blob_sha1=alarm_source_git_blob,
        )
        LOG.info("Source mode: explicit pinned local source")

    source_hash = source_provenance["sha256"]
    source_identity = {
        "sha256": source_hash,
        "upstream_commit": source_provenance.get("resolved_upstream_commit_sha"),
        "upstream_git_blob": source_provenance.get("upstream_git_blob_sha1"),
        "project_fingerprint": fingerprint,
    }
    if previous and resume and not fresh:
        if previous.get("source_identity") != source_identity:
            raise RuntimeError(
                "Existing checkpoints belong to a different source commit/blob/SHA-256 or project fingerprint. "
                "Start a clean build with './run_local.sh fresh-build'."
            )
    elif not resume and output_dir.exists():
        clean_dir(output_dir)
        ensure_dir(output_dir)
        configure_logging(output_dir / "logs/build.log")

    if previous and previous.get("source_preparation", {}).get("status") == "PASS" and (prepared_dir / "source_preparation.json").exists():
        prep = read_json(prepared_dir / "source_preparation.json")
        LOG.info("Resuming from validated source preparation")
    else:
        LOG.info("Validating, deduplicating and partitioning the source")
        prep = prepare_alarm_source(
            alarm_source=alarm_source,
            output_dir=prepared_dir,
            geography=geography,
            assumptions=assumptions,
            source_contract=sources["air_alarm_source"],
            clean=True,
        )

    coverage_start = parse_datetime_utc(prep["coverage_start_utc"])
    coverage_end = parse_datetime_utc(prep["coverage_end_utc"])
    batch_total = len(years) * len(areas)
    completed: list[dict[str, str]] = []
    failed: list[dict[str, str]] = []
    build_started = previous.get("build_started_at_utc") if previous else utc_now_iso()

    state = {
        "status": "RUNNING",
        "build_started_at_utc": build_started,
        "last_updated_at_utc": utc_now_iso(),
        "source_filename": alarm_source.name,
        "source_sha256": source_hash,
        "source_identity": source_identity,
        "source_provenance": source_provenance,
        "project_fingerprint": fingerprint,
        "school_years": years,
        "oblast_ids": areas,
        "batch_total": batch_total,
        "source_preparation": {"status": "PASS", "preparation_id": prep["preparation_id"]},
        "completed_batches": previous.get("completed_batches", []) if previous else [],
        "failed_batches": [],
    }
    completed_keys = {(x["school_year"], x["oblast_id"]) for x in state["completed_batches"]}
    write_json(state_path, state)

    for school_year in years:
        year_start, year_end = _school_year_coverage_bounds(root, assumptions, school_year)
        effective_start = max(coverage_start, year_start)
        effective_end = min(coverage_end, year_end)
        if effective_end <= effective_start:
            LOG.warning("No source coverage intersects %s; output will be unavailable", school_year)
            effective_start, effective_end = coverage_start, coverage_end
        for oblast_id in areas:
            key = (school_year, oblast_id)
            batch_dir = batches_dir / school_year / oblast_id
            partition = prepared_dir / "partitions" / f"{oblast_id}.csv.gz"
            if key in completed_keys and (batch_dir / "audit/audit_summary.json").exists():
                LOG.info("Skipping completed batch %s / %s", school_year, oblast_id)
                continue
            if not partition.exists():
                ensure_dir(partition.parent)
                import gzip
                with gzip.open(partition, "wt", encoding="utf-8", newline="") as handle:
                    writer = csv.DictWriter(handle, fieldnames=["oblast", "raion", "hromada", "level", "started_at", "finished_at", "source"])
                    writer.writeheader()
            LOG.info("Building batch %s / %s", school_year, oblast_id)
            try:
                audit = run_build(
                    root=root,
                    output_dir=batch_dir,
                    alarm_source=partition,
                    school_year=school_year,
                    coverage_start_utc=coverage_start,
                    coverage_end_utc=coverage_end,
                    oblast_ids=[oblast_id],
                    clean=True,
                    download_if_missing=False,
                    source_filter_start_utc=year_start,
                    source_filter_end_utc=year_end,
                    controlled_input_root=controlled_input_root,
                    source_provenance={
                        "source_mode": "prepared_immutable_partition",
                        "parent_source_identity": source_identity,
                    },
                )
                if audit["status"] != "PASS":
                    raise RuntimeError(f"Batch returned {audit['status']}")
                item = {"school_year": school_year, "oblast_id": oblast_id, "build_id": audit["build_id"]}
                state["completed_batches"] = [x for x in state["completed_batches"] if (x["school_year"], x["oblast_id"]) != key]
                state["completed_batches"].append(item)
                completed_keys.add(key)
                completed.append(item)
            except Exception as exc:
                failure = {"school_year": school_year, "oblast_id": oblast_id, "error": str(exc)}
                state["failed_batches"].append(failure)
                failed.append(failure)
                LOG.exception("Batch failed: %s / %s", school_year, oblast_id)
            state["last_updated_at_utc"] = utc_now_iso()
            state["status"] = "RUNNING" if not failed else "PARTIAL"
            write_json(state_path, state)

    if failed:
        state["status"] = "PARTIAL"
        state["last_updated_at_utc"] = utc_now_iso()
        write_json(state_path, state)
        return state

    LOG.info("Consolidating completed batches")
    final_summary = consolidate_batches(
        root=root,
        output_dir=output_dir,
        final_dir=final_dir,
        school_years=years,
        oblast_ids=areas,
        source_preparation=prep,
        source_hash=source_hash,
        project_fingerprint=fingerprint,
        source_provenance=source_provenance,
        governed_versions=governed_versions,
    )
    state["status"] = final_summary["status"]
    state["final_build_id"] = final_summary["build_id"]
    state["last_updated_at_utc"] = utc_now_iso()
    state["failed_batches"] = []
    write_json(state_path, state)
    return state


def _read_typed_rows(path: Path) -> list[dict[str, Any]]:
    rows = read_csv_rows(path)
    for row in rows:
        for field in NUMERIC_INT_FIELDS:
            if field in row:
                row[field] = None if row[field] == "" else int(float(row[field]))
        for field in NUMERIC_FLOAT_FIELDS:
            if field in row:
                row[field] = None if row[field] == "" else float(row[field])
    return rows


def consolidate_batches(
    *,
    root: Path,
    output_dir: Path,
    final_dir: Path,
    school_years: list[str],
    oblast_ids: list[str],
    source_preparation: dict[str, Any],
    source_hash: str,
    project_fingerprint: str,
    source_provenance: dict[str, Any],
    governed_versions: dict[str, str],
) -> dict[str, Any]:
    clean_dir(final_dir)
    analytical_dir = ensure_dir(final_dir / "analytical")
    payload_dir = ensure_dir(final_dir / "payloads")
    audit_dir = ensure_dir(final_dir / "audit")

    hromada_monthly: list[dict[str, Any]] = []
    hromada_school_year: list[dict[str, Any]] = []
    batch_audits: list[dict[str, Any]] = []
    batch_unmapped: list[dict[str, Any]] = []
    batch_education_issues: list[dict[str, Any]] = []
    batch_invalid: list[dict[str, Any]] = []
    batch_coverage: list[dict[str, Any]] = []
    for school_year in school_years:
        for oblast_id in oblast_ids:
            batch_dir = output_dir / "batches" / school_year / oblast_id
            hromada_monthly.extend(_read_typed_rows(batch_dir / "analytical/hromada_monthly.csv"))
            hromada_school_year.extend(_read_typed_rows(batch_dir / "analytical/hromada_school_year.csv"))
            batch_audits.append(read_json(batch_dir / "audit/audit_summary.json"))
            for filename, target in [
                ("unmapped_alert_geographies.csv", batch_unmapped),
                ("education_data_issues.csv", batch_education_issues),
                ("invalid_alert_rows.csv", batch_invalid),
                ("geographic_coverage.csv", batch_coverage),
            ]:
                for item in read_csv_rows(batch_dir / "audit" / filename):
                    target.append({"school_year": school_year, "oblast_id": oblast_id, **item})

    hromada_monthly.sort(key=lambda r: (r["school_year"], r["period_id"], r["oblast_id"], r["hromada_id"]))
    hromada_school_year.sort(key=lambda r: (r["school_year"], r["oblast_id"], r["hromada_id"]))
    oblast_monthly = aggregate_multi_area(hromada_monthly, "oblast")
    oblast_school_year = aggregate_multi_area(hromada_school_year, "oblast")
    national_monthly = aggregate_multi_area(hromada_monthly, "national")
    national_school_year = aggregate_multi_area(hromada_school_year, "national")

    datasets = {
        "hromada_monthly.csv": hromada_monthly,
        "hromada_school_year.csv": hromada_school_year,
        "oblast_monthly.csv": oblast_monthly,
        "oblast_school_year.csv": oblast_school_year,
        "national_monthly.csv": national_monthly,
        "national_school_year.csv": national_school_year,
    }
    for name, rows in datasets.items():
        write_csv_rows(analytical_dir / name, rows)

    build_id = "AAE-FULL-" + stable_id(
        source_hash,
        source_provenance.get("resolved_upstream_commit_sha"),
        source_provenance.get("upstream_git_blob_sha1"),
        project_fingerprint,
        *school_years,
        *oblast_ids,
        length=18,
    )
    complete_source_provenance = {
        **source_provenance,
        "input_row_count": source_preparation["input_row_count"],
        "valid_unique_row_count": source_preparation["valid_unique_source_row_count"],
        "mapped_valid_unique_row_count": source_preparation["mapped_valid_unique_row_count"],
        "invalid_row_count": source_preparation["invalid_row_count"],
        "exact_duplicate_row_count": source_preparation["exact_duplicate_row_count"],
        "coverage_start_utc": source_preparation["coverage_start_utc"],
        "coverage_end_utc": source_preparation["coverage_end_utc"],
        "declared_level_counts": source_preparation["declared_level_counts"],
        "mapping_route_counts": source_preparation["mapping_route_counts"],
        "unmapped_by_declared_level": source_preparation["unmapped_by_declared_level"],
        "detailed_mapping_failure_count": source_preparation["detailed_mapping_failure_count"],
    }
    metadata = {
        "build_id": build_id,
        "build_completed_at_utc": utc_now_iso(),
        **governed_versions,
        "school_years": school_years,
        "oblast_ids": oblast_ids,
        "source_url": source_provenance.get("immutable_resolved_raw_url"),
        "configured_source_url": source_provenance.get("configured_source_url"),
        "source_sha256": source_hash,
        "source_coverage_start_utc": source_preparation["coverage_start_utc"],
        "source_coverage_end_utc": source_preparation["coverage_end_utc"],
        "source_provenance": complete_source_provenance,
        "project_fingerprint": project_fingerprint,
        "project_inventory": project_inventory(root),
    }
    payload_manifest = build_payloads(
        payload_dir, metadata, hromada_monthly, hromada_school_year,
        oblast_monthly, oblast_school_year, national_monthly, national_school_year,
    )

    checks = build_full_checks(
        hromada_monthly=hromada_monthly,
        hromada_school_year=hromada_school_year,
        oblast_monthly=oblast_monthly,
        oblast_school_year=oblast_school_year,
        national_monthly=national_monthly,
        national_school_year=national_school_year,
        payload_dir=payload_dir,
        payload_manifest=payload_manifest,
        school_years=school_years,
        oblast_ids=oblast_ids,
        batch_audits=batch_audits,
        source_preparation=source_preparation,
    )
    write_csv_rows(audit_dir / "indicator_reconciliation.csv", checks)
    hard_failures = [c for c in checks if c["status"] == "FAIL"]
    review_flags = (
        source_preparation["invalid_row_count"]
        + source_preparation["long_interval_review_row_count"]
        + sum(a["unmapped_alert_rows"] + a["education_issue_rows"] for a in batch_audits)
    )
    status = "FAIL" if hard_failures else ("PASS_WITH_REVIEW_FLAGS" if review_flags else "PASS")

    batch_summary_rows = []
    for school_year, oblast_id, audit in zip(
        [y for y in school_years for _ in oblast_ids],
        [o for _ in school_years for o in oblast_ids],
        batch_audits,
    ):
        batch_summary_rows.append({"school_year": school_year, "oblast_id": oblast_id, **audit})
    write_csv_rows(audit_dir / "batch_summary.csv", batch_summary_rows)
    write_csv_rows(audit_dir / "batch_unmapped_alert_geographies.csv", batch_unmapped)
    write_csv_rows(audit_dir / "batch_education_data_issues.csv", batch_education_issues)
    write_csv_rows(audit_dir / "batch_invalid_alert_rows.csv", batch_invalid)
    write_csv_rows(audit_dir / "batch_geographic_coverage.csv", batch_coverage)

    source_audit_dir = output_dir / "prepared_source/audit"
    for source_file in source_audit_dir.glob("*"):
        shutil.copy2(source_file, audit_dir / f"source_{source_file.name}")
    write_json(audit_dir / "source_preparation.json", source_preparation)

    qa = {
        "build_id": build_id,
        "status": status,
        "review_status": "READY_FOR_INDEPENDENT_REVIEW" if not hard_failures else "REPAIR_REQUIRED",
        "hard_failure_count": len(hard_failures),
        "review_flag_count": review_flags,
        "checks_passed": sum(c["status"] == "PASS" for c in checks),
        "checks_total": len(checks),
        "row_counts": {name.removesuffix(".csv"): len(rows) for name, rows in datasets.items()},
        "source_counts": {
            "input_rows": source_preparation["input_row_count"],
            "duplicate_rows": source_preparation["exact_duplicate_row_count"],
            "invalid_rows": source_preparation["invalid_row_count"],
            "unmapped_oblast_rows": source_preparation["unmapped_oblast_row_count"],
            "unmapped_raion_rows": source_preparation["unmapped_raion_row_count"],
            "unmapped_hromada_rows": source_preparation["unmapped_hromada_row_count"],
            "unsupported_level_rows": source_preparation["unsupported_level_row_count"],
            "ambiguous_mapping_rows": source_preparation["ambiguous_mapping_row_count"],
            "long_interval_rows": source_preparation["long_interval_review_row_count"],
        },
    }
    write_json(audit_dir / "qa_summary.json", qa)
    output_files = [p for p in final_dir.rglob("*") if p.is_file() and p.name != "build_manifest.json"]
    manifest = {**metadata, "status": status, "qa_summary": qa, "outputs": file_inventory(final_dir, output_files)}
    write_json(audit_dir / "build_manifest.json", manifest)
    return qa


def build_full_checks(
    *,
    hromada_monthly: list[dict[str, Any]],
    hromada_school_year: list[dict[str, Any]],
    oblast_monthly: list[dict[str, Any]],
    oblast_school_year: list[dict[str, Any]],
    national_monthly: list[dict[str, Any]],
    national_school_year: list[dict[str, Any]],
    payload_dir: Path,
    payload_manifest: dict[str, Any],
    school_years: list[str],
    oblast_ids: list[str],
    batch_audits: list[dict[str, Any]],
    source_preparation: dict[str, Any],
) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []

    def add(check_id: str, passed: bool, difference: Any) -> None:
        checks.append({"check_id": check_id, "status": "PASS" if passed else "FAIL", "difference": difference})

    datasets = {
        "HROMADA_MONTHLY": (hromada_monthly, lambda r: (r["school_year"], r["period_id"], r["hromada_id"])),
        "HROMADA_YEAR": (hromada_school_year, lambda r: (r["school_year"], r["hromada_id"])),
        "OBLAST_MONTHLY": (oblast_monthly, lambda r: (r["school_year"], r["period_id"], r["area_id"])),
        "OBLAST_YEAR": (oblast_school_year, lambda r: (r["school_year"], r["area_id"])),
        "NATIONAL_MONTHLY": (national_monthly, lambda r: (r["school_year"], r["period_id"], r["area_id"])),
        "NATIONAL_YEAR": (national_school_year, lambda r: (r["school_year"], r["area_id"])),
    }
    for label, (rows, key_fn) in datasets.items():
        keys = [key_fn(row) for row in rows]
        add(f"{label}_KEYS_UNIQUE", len(keys) == len(set(keys)), len(keys) - len(set(keys)))

    def month_year_reconciliation(
        monthly: list[dict[str, Any]],
        yearly: list[dict[str, Any]],
        area_field: str,
        alarm_field: str,
    ) -> float:
        sums: dict[tuple[str, str], float] = {}
        for row in monthly:
            key = (row["school_year"], row[area_field])
            sums[key] = sums.get(key, 0.0) + float(row.get(alarm_field) or 0)
        return max(
            [
                abs(
                    sums.get((row["school_year"], row[area_field]), 0.0)
                    - float(row.get(alarm_field) or 0)
                )
                for row in yearly
            ]
            or [0.0]
        )

    reconciliation_specs = [
        ("HROMADA", hromada_monthly, hromada_school_year, "hromada_id", "alarm_seconds", 0.5),
        ("OBLAST", oblast_monthly, oblast_school_year, "area_id", "alarm_seconds_average_school_location", 1e-6),
        ("NATIONAL", national_monthly, national_school_year, "area_id", "alarm_seconds_average_school_location", 1e-6),
    ]
    for label, monthly, yearly, area_field, alarm_field, tolerance in reconciliation_specs:
        difference = month_year_reconciliation(monthly, yearly, area_field, alarm_field)
        add(f"{label}_MONTH_TO_YEAR_ALARM_RECONCILIATION", difference < tolerance, difference)

    pct_diff = 0.0
    for rows, alarm_field, available_field in [
        (hromada_monthly + hromada_school_year, "alarm_seconds", "available_school_seconds"),
        (
            oblast_monthly + oblast_school_year + national_monthly + national_school_year,
            "alarm_seconds_average_school_location",
            "available_school_seconds_average_school_location",
        ),
    ]:
        for row in rows:
            available = float(row.get(available_field) or 0)
            if available > 0:
                expected = float(row.get(alarm_field) or 0) / available * 100
                pct_diff = max(pct_diff, abs(expected - float(row["school_time_under_alarm_pct"])))
    add("ALL_PERCENTAGES_RECONCILE", pct_diff < 1e-9, pct_diff)

    expected_batches = len(school_years) * len(oblast_ids)
    add("ALL_BATCHES_PRESENT", len(batch_audits) == expected_batches, expected_batches - len(batch_audits))
    add("ALL_BATCH_CHECKS_PASS", all(a.get("status") == "PASS" for a in batch_audits), sum(a.get("status") != "PASS" for a in batch_audits))
    add(
        "NO_BATCH_UNMAPPED_OFFICIAL_ROWS",
        all(int(a.get("unmapped_alert_rows", 0)) == 0 for a in batch_audits),
        sum(int(a.get("unmapped_alert_rows", 0)) for a in batch_audits),
    )
    add(
        "EDUCATION_BATCH_CHECKS_PRESENT",
        all(int(a.get("checks_total", 0)) >= 6 for a in batch_audits),
        sum(int(a.get("checks_total", 0)) < 6 for a in batch_audits),
    )

    mapping_failures = int(source_preparation.get("detailed_mapping_failure_count", -1))
    mapping_count_difference = int(source_preparation.get("valid_unique_source_row_count", 0)) - int(
        source_preparation.get("mapped_valid_unique_row_count", -1)
    )
    add("DETAILED_SOURCE_MAPPING_HARD_GATE", mapping_failures == 0, mapping_failures)
    add("ALL_VALID_UNIQUE_SOURCE_ROWS_MAPPED", mapping_count_difference == 0, mapping_count_difference)
    add(
        "SOURCE_DOMAIN_OFFICIAL_ONLY",
        set(source_preparation.get("source_value_counts", {})) == {"official"},
        source_preparation.get("source_value_counts", {}),
    )

    def max_aggregate_difference(
        expected: list[dict[str, Any]],
        actual: list[dict[str, Any]],
    ) -> float:
        key_fields = ("school_year", "period_id", "area_id")
        numeric_fields = (
            "alarm_seconds_average_school_location",
            "available_school_seconds_average_school_location",
            "expected_school_seconds_average_school_location",
            "school_time_under_alarm_pct",
            "affected_school_days_average_school_location",
            "available_school_days_average_school_location",
            "expected_school_days_average_school_location",
        )
        actual_by_key = {tuple(row[field] for field in key_fields): row for row in actual}
        maximum = 0.0
        if len(expected) != len(actual):
            return float("inf")
        for expected_row in expected:
            key = tuple(expected_row[field] for field in key_fields)
            actual_row = actual_by_key.get(key)
            if actual_row is None:
                return float("inf")
            for field in numeric_fields:
                maximum = max(
                    maximum,
                    abs(float(expected_row.get(field) or 0) - float(actual_row.get(field) or 0)),
                )
        return maximum

    weighting_checks = [
        ("OBLAST_MONTHLY", aggregate_multi_area(hromada_monthly, "oblast"), oblast_monthly),
        ("OBLAST_YEAR", aggregate_multi_area(hromada_school_year, "oblast"), oblast_school_year),
        ("NATIONAL_MONTHLY", aggregate_multi_area(hromada_monthly, "national"), national_monthly),
        ("NATIONAL_YEAR", aggregate_multi_area(hromada_school_year, "national"), national_school_year),
    ]
    for label, expected, actual in weighting_checks:
        difference = max_aggregate_difference(expected, actual)
        add(f"{label}_ACTIVE_SCHOOL_LOCATION_WEIGHTING", difference < 1e-9, difference)

    education_difference = 0
    for rows in [oblast_monthly, oblast_school_year, national_monthly, national_school_year]:
        for row in rows:
            if int(row.get("school_count") or 0) < 0 or int(row.get("learners_total") or 0) < 0:
                education_difference += 1
    add("EDUCATION_TOTALS_NON_NEGATIVE", education_difference == 0, education_difference)

    missing_payloads = [item["path"] for item in payload_manifest["payload_files"] if not (payload_dir / item["path"]).exists()]
    add("PAYLOAD_FILES_EXIST", not missing_payloads, len(missing_payloads))
    analytical_payloads = [item for item in payload_manifest["payload_files"] if item["path"] != "metadata.json"]
    expected_payload_count = 4 + 2 * len(oblast_ids)
    add(
        "ANALYTICAL_PAYLOAD_COUNT_EXPECTED",
        len(analytical_payloads) == expected_payload_count,
        {"actual": len(analytical_payloads), "expected": expected_payload_count},
    )
    if len(oblast_ids) == 26:
        add("FULL_NATIONAL_ANALYTICAL_PAYLOAD_COUNT_56", len(analytical_payloads) == 56, len(analytical_payloads))

    def public_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [
            {key: round(value, 6) if isinstance(value, float) else value for key, value in row.items()}
            for row in rows
        ]

    payload_differences = 0
    direct_payloads = {
        "national_monthly.json": national_monthly,
        "national_school_year.json": national_school_year,
        "oblast_monthly.json": oblast_monthly,
        "oblast_school_year.json": oblast_school_year,
    }
    for filename, expected_rows in direct_payloads.items():
        if read_json(payload_dir / filename) != public_rows(expected_rows):
            payload_differences += 1
    for oblast_id in oblast_ids:
        expected_month = [row for row in hromada_monthly if row["oblast_id"] == oblast_id]
        expected_year = [row for row in hromada_school_year if row["oblast_id"] == oblast_id]
        if read_json(payload_dir / "hromada_monthly_by_oblast" / f"{oblast_id}.json") != public_rows(expected_month):
            payload_differences += 1
        if read_json(payload_dir / "hromada_school_year_by_oblast" / f"{oblast_id}.json") != public_rows(expected_year):
            payload_differences += 1
    add("CANONICAL_TO_PAYLOAD_CORRESPONDENCE", payload_differences == 0, payload_differences)
    return checks
