const echarts = window.echarts;
import { affectedDaysPct, formatNumber, isAnalyticallyUnavailable, monthLabel, SCHOOL_YEAR_LABELS } from './logic.js';
const charts = new WeakMap();
function instance(el) { const old = charts.get(el); if (old) {
    old.dispose();
} const c = echarts.init(el, null, { renderer: 'svg' }); charts.set(el, c); return c; }
function val(r, m) { return isAnalyticallyUnavailable(r) ? null : m === 'affected_school_days_pct' ? affectedDaysPct(r) : r[m]; }
export function monthlyChart(el, rows, measure, lang, onMonth) { const c = instance(el), data = rows.sort((a, b) => a.period_id.localeCompare(b.period_id)); c.setOption({ aria: { enabled: true, decal: { show: true } }, tooltip: { trigger: 'axis' }, grid: { left: 52, right: 16, top: 30, bottom: 48 }, xAxis: { type: 'category', data: data.map(r => monthLabel(r.period_id, lang, true)), axisLabel: { rotate: 30 } }, yAxis: { type: 'value' }, series: [{ type: 'bar', data: data.map(r => val(r, measure)), itemStyle: { color: '#286B8D' }, emphasis: { focus: 'series' } }] }); c.on('click', (p) => { const r = data[p.dataIndex]; if (r)
    onMonth(r.period_id); }); return c; }
export function schoolYearChart(el, rows, measure, lang) { const c = instance(el), data = rows.sort((a, b) => a.school_year.localeCompare(b.school_year)); c.setOption({ aria: { enabled: true, decal: { show: true } }, tooltip: { trigger: 'axis' }, grid: { left: 52, right: 16, top: 30, bottom: 35 }, xAxis: { type: 'category', data: data.map(r => SCHOOL_YEAR_LABELS[r.school_year]) }, yAxis: { type: 'value' }, series: [{ type: 'line', smooth: false, symbolSize: 9, data: data.map(r => val(r, measure)), lineStyle: { width: 3, color: '#286B8D' }, itemStyle: { color: '#286B8D' } }] }); return c; }
export function heatmapChart(el, rows, lang) { const c = instance(el); const years = [...new Set(rows.map(r => r.school_year))]; const months = ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']; const monthUk = ['Вер', 'Жов', 'Лис', 'Гру', 'Січ', 'Лют', 'Бер', 'Кві', 'Тра', 'Чер']; const data = rows.map(r => { const m = Number(r.period_id.slice(5)); const idx = m >= 9 ? m - 9 : m + 3; return [idx, years.indexOf(r.school_year), r.school_time_under_alarm_pct ?? null]; }); c.setOption({ aria: { enabled: true, decal: { show: true } }, tooltip: { formatter: (p) => `${SCHOOL_YEAR_LABELS[years[p.value[1]]]} · ${(lang === 'uk' ? monthUk : months)[p.value[0]]}: ${formatNumber(p.value[2], lang, 1)}%` }, grid: { left: 70, right: 55, top: 20, bottom: 45 }, xAxis: { type: 'category', data: lang === 'uk' ? monthUk : months }, yAxis: { type: 'category', data: years.map(y => SCHOOL_YEAR_LABELS[y]) }, visualMap: { min: 0, max: Math.max(1, ...data.map(x => Number(x[2] ?? 0))), calculable: false, orient: 'vertical', right: 0, top: 'middle' }, series: [{ type: 'heatmap', data, label: { show: false }, emphasis: { itemStyle: { shadowBlur: 5 } } }] }); return c; }
export function modalityChart(el, rows, lang) { const c = instance(el); const categories = rows.map(r => SCHOOL_YEAR_LABELS[r.school_year]); const series = [['Offline', rows.map(r => r.learners_offline)], ['Online', rows.map(r => r.learners_online)], ['Mixed', rows.map(r => r.school_year === '2022_2023' ? null : r.learners_mixed)], ['Other', rows.map(r => r.school_year === '2022_2023' ? null : Math.max(0, r.learners_total - r.learners_offline - r.learners_online - r.learners_mixed))]]; c.setOption({ aria: { enabled: true, decal: { show: true } }, tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } }, legend: { bottom: 0 }, grid: { left: 70, right: 15, top: 20, bottom: 55 }, xAxis: { type: 'value' }, yAxis: { type: 'category', data: categories }, series: series.map(([name, data]) => ({ name, type: 'bar', stack: 'total', data })) }); return c; }
export function resizeCharts() { charts; document.querySelectorAll('.chart').forEach(el => charts.get(el)?.resize()); }
