export const resources = {
    uk: {
        translation: {
            appTitle: 'Як повітряні тривоги переривають навчальний день в Україні',
            subtitle: 'Оцінка перетину зафіксованих повітряних тривог із припущеним часом роботи закладів освіти.',
            releaseStatus: 'Фінальний публічний реліз',
            skipToContent: 'Перейти до основного вмісту',
            language: 'Мова',
            supportingPages: 'Довідкові сторінки',
            chooseView: 'Налаштуйте перегляд',
            territory: 'Територія',
            territoryHint: 'Пошук області, громади або коду КАТОТТГ',
            period: 'Період',
            wholeSchoolYear: 'Весь навчальний рік',
            schoolYear: 'Навчальний рік',
            month: 'Місяць',
            customRange: 'Власний діапазон',
            allAvailable: 'Усі доступні дані',
            allAvailableNote: 'Увесь період, доступний у цьому аналітичному релізі.',
            from: 'Від',
            to: 'До',
            reset: 'Скинути налаштування',
            backToOblast: '← Назад до області: {{oblast}}',
            atGlance: 'Основні результати',
            keyMeasures: 'Ключові показники',
            alarmTime: 'Час тривог у межах навчального дня',
            affectedDays: 'Навчальні дні з тривогами',
            episodes: 'Епізоди тривог у межах навчального дня',
            indicatorInfo: 'Пояснення показника',
            educationContext: 'Освітній контекст',
            schools: 'Заклади освіти',
            learners: 'Учні',
            snapshot: 'Дані станом на',
            modalityDetails: 'Розподіл учнів за формами навчання',
            modalityChartIntro: 'Контекстні дані про мережу закладів освіти; це не спостережувана присутність учнів під час тривог.',
            modalityChartLabel: 'Розподіл учнів за формами навчання і навчальними роками',
            offline: 'Очна',
            offlineDerived: 'Очна (розраховано)',
            online: 'Дистанційна',
            mixed: 'Змішана',
            other: 'Інші форми',
            educationUnavailable: 'Для вибраної території та періоду освітній контекст недоступний.',
            overTime: 'Динаміка в часі',
            trendMeasure: 'Показник',
            trendView: 'Режим часової візуалізації',
            monthlyTrend: 'Щомісячна динаміка',
            schoolYearComparison: 'Порівняння навчальних років',
            heatmap: 'Місяці за навчальними роками',
            monthlyChartLabel: 'Щомісячна динаміка вибраного показника',
            yearChartLabel: 'Порівняння вибраного показника за навчальними роками',
            heatmapChartLabel: 'Значення вибраного показника за місяцями й навчальними роками',
            hours: 'Час під тривогами (години)',
            alarmShare: 'Частка навчального часу',
            daysShare: 'Частка навчальних днів',
            dataTable: 'Таблиця даних',
            chartUnavailable: 'Візуалізація недоступна; значення залишаються в таблиці даних.',
            acrossPlaces: 'За територіями',
            map: 'Карта',
            mapLabel: 'Карта України з аналітичними значеннями за територіями',
            colourBy: 'Колір за показником',
            fitSelected: 'Показати вибрану територію',
            resetMap: 'Показати всю карту',
            mapFitSuccess: 'Карту наближено до вибраної території.',
            mapFitUnavailable: 'Геометрія вибраної громади недоступна; показано її область.',
            mapResetSuccess: 'Показано всю доступну карту.',
            mapUnavailable: 'Карта недоступна; територію можна вибрати через пошук або таблицю порівняння.',
            compareAreas: 'Порівняння територій',
            filterAreas: 'Фільтр територій',
            areasShown: 'Показано територій: {{count}}',
            tableNoResults: 'За цим запитом територій не знайдено.',
            downloadCsv: 'Завантажити CSV',
            csvPrepared: 'CSV підготовлено для територій: {{count}}.',
            selectArea: 'Перейти до території',
            currentArea: 'Вибрана територія',
            sortAscending: 'Сортування за зростанням',
            sortDescending: 'Сортування за спаданням',
            interpret: 'Як тлумачити результати',
            methodology: 'Методологія',
            dataRelease: 'Дані та реліз',
            backDashboard: 'Назад до дашборду',
            formula: 'Формула',
            aggregateTreatment: 'Агрегування',
            assumption: 'Ключове припущення',
            notMeasured: 'Що не вимірюється',
            close: 'Закрити',
            unavailable: 'Недоступно',
            partial: 'Часткове охоплення',
            complete: 'Повне охоплення',
            noEpisodesRange: 'Для довільного діапазону окремий підсумок епізодів недоступний: один епізод може перетинати межу місяця.',
            multiYearContext: 'Освітній контекст наведено окремо за кожним навчальним роком; кількість учнів між роками не підсумовується.',
            contextCaveat: 'Показники освіти описують мережу закладів і не є даними про фактичну присутність під час тривог.',
            modality2022: 'У 2022/23 кількість учнів на очній формі розраховано як загальну кількість мінус кількість на дистанційній формі; детальнішої класифікації тоді не було.',
            modalityLater: 'У наступні роки очну, дистанційну та змішану форми наведено окремо; «інші форми» — розрахунковий залишок, що переважно охоплює неочні форми, зокрема сімейну та споріднені форми навчання.',
            mapAlternative: 'Ті самі значення та вибір території доступні в таблиці порівняння.',
            methodQuestion: 'Що саме оцінює дашборд?',
            methodQuestionText: 'Дашборд оцінює перетин зафіксованих інтервалів повітряних тривог із припущеним навчальним часом. Він не спостерігає фактичні розклади, відвідування чи проведення уроків.',
            sources: 'Джерела та охоплення',
            assumptions: 'Припущення',
            processing: 'Обробка інтервалів тривог',
            geography: 'Географічний розподіл',
            indicators: 'Показники та формули',
            weighting: 'Агрегування і діапазони',
            education: 'Освітній контекст',
            missingness: 'Нуль, часткове охоплення і недоступність',
            limitations: 'Обмеження та належне використання',
            limitationsText: 'Дашборд не вимірює навчальні втрати, фактично скасовані уроки, відвідування, фактичний час в укриттях, реальні розклади, порушення виконання домашніх завдань, порушення сну чи індивідуальний вплив на учнів.',
            workedExample: 'Приклад розрахунку',
            releaseInfo: 'Відомості про реліз',
            architecture: 'Архітектура публікації',
            loading: 'Завантаження даних…',
            fatal: 'Не вдалося завантажити дані дашборду.',
            fatalHelp: 'Оновіть сторінку або спробуйте пізніше.',
            releaseMismatch: 'Метадані релізу не узгоджені.',
            invalidParams: 'Деякі некоректні параметри посилання замінено безпечними значеннями.',
            searchNoResults: 'Нічого не знайдено',
            area: 'Територія',
            share: 'Частка часу',
            days: 'Частка днів',
            precision: 'Географічна точність',
            coverage: 'Охоплення',
            averageLocation: 'У середньому на одне активне місце розташування закладу освіти.',
            directResult: 'Показник, безпосередньо розрахований для громади.',
            aggregateMetricContext: 'Для України та областей абсолютні значення є середніми на одне активне місце розташування закладу; частки обчислено з відповідних зважених чисельників і знаменників.',
            loadingArea: 'Завантаження даних вибраної області…',
            loadAreaFailed: 'Не вдалося завантажити дані вибраної області. Повторіть спробу.',
            geometryUnavailable: 'Для вибраної громади немає контрольованої геометрії; аналітичні результати й табличний вибір залишаються доступними.',
            analyticalUnavailable: 'Для цієї території та періоду аналітичний результат недоступний; нуль не підставлено.',
            noData: 'Для вибраної території та періоду немає доступного рядка даних.',
            sourcePrecisionMixed: 'Змішана географічна точність',
            sourcePrecisionNotApplicable: 'Не застосовується',
            sourcePrecisionOblast: 'Розподілено з рівня області',
            sourcePrecisionRaion: 'Розподілено з рівня району',
            alarmMeaning: 'Сумарна тривалість об’єднаних інтервалів тривог, що перетинаються з припущеним навчальним вікном.',
            alarmFormula: 'секунди перетину ÷ 3 600; частка = секунди перетину ÷ доступні припущені навчальні секунди × 100',
            alarmAssumption: 'Понеділок–п’ятниця, визначені канікули, 08:00–15:00 за Europe/Kyiv.',
            alarmNot: 'Фактично скасовані уроки, відвідування або навчальні втрати.',
            daysMeaning: 'День враховано, якщо в межах припущеного навчального часу є хоча б один додатний перетин із тривогою.',
            daysFormula: 'дні з додатним перетином ÷ доступні припущені навчальні дні × 100',
            daysAssumption: 'До знаменника входять лише доступні припущені навчальні дні.',
            daysNot: 'Чи було навчання припинено на весь день.',
            episodesMeaning: 'Кількість окремих оброблених епізодів тривог із додатним перетином у межах навчального дня.',
            episodesFormula: 'кількість окремих ідентифікаторів оброблених епізодів із додатним перетином',
            episodesAssumption: 'Тривалий епізод, що перетинає межу днів, враховується один раз.',
            episodesNot: 'Суму місячних епізодів для довільного багатомісячного діапазону.'
        }
    },
    en: {
        translation: {
            appTitle: 'How Air Alarms Disrupt the School Day in Ukraine',
            subtitle: 'Estimated overlap between recorded air alarms and assumed school operating hours.',
            releaseStatus: 'Production release',
            skipToContent: 'Skip to main content',
            language: 'Language',
            supportingPages: 'Supporting pages',
            chooseView: 'Set the view',
            territory: 'Territory',
            territoryHint: 'Search by oblast, hromada or KATOTTG code',
            period: 'Period',
            wholeSchoolYear: 'Whole school year',
            schoolYear: 'School year',
            month: 'Month',
            customRange: 'Custom range',
            allAvailable: 'All available data',
            allAvailableNote: 'The full period available in this analytical release.',
            from: 'From',
            to: 'To',
            reset: 'Reset settings',
            backToOblast: '← Back to oblast: {{oblast}}',
            atGlance: 'Key result',
            keyMeasures: 'Key measures',
            alarmTime: 'Alarm time within the school day',
            affectedDays: 'School days affected',
            episodes: 'Alarm episodes within the school day',
            indicatorInfo: 'Indicator explanation',
            educationContext: 'Education context',
            schools: 'Schools',
            learners: 'Learners',
            snapshot: 'Data as of',
            modalityDetails: 'Learners by education modality',
            modalityChartIntro: 'Contextual education-network figures; these are not observed learner presence during alarms.',
            modalityChartLabel: 'Learners by education modality and school year',
            offline: 'In-person',
            offlineDerived: 'In-person (derived)',
            online: 'Remote',
            mixed: 'Mixed',
            other: 'Other modalities',
            educationUnavailable: 'Education context is unavailable for the selected territory and period.',
            overTime: 'Change over time',
            trendMeasure: 'Measure',
            trendView: 'Time-chart view',
            monthlyTrend: 'Monthly trend',
            schoolYearComparison: 'School-year comparison',
            heatmap: 'Months by school year',
            monthlyChartLabel: 'Monthly trend for the selected measure',
            yearChartLabel: 'Selected measure compared across school years',
            heatmapChartLabel: 'Selected measure by month and school year',
            hours: 'Alarm overlap (hours)',
            alarmShare: 'Share of school time',
            daysShare: 'Share of school days',
            dataTable: 'Data table',
            chartUnavailable: 'The visualisation is unavailable; values remain available in the data table.',
            acrossPlaces: 'Across territories',
            map: 'Map',
            mapLabel: 'Map of Ukraine with analytical values by territory',
            colourBy: 'Colour by measure',
            fitSelected: 'Fit selected area',
            resetMap: 'Show full map',
            mapFitSuccess: 'The map is fitted to the selected area.',
            mapFitUnavailable: 'Geometry for the selected hromada is unavailable; its oblast is shown.',
            mapResetSuccess: 'The full available map is shown.',
            mapUnavailable: 'The map is unavailable; use search or the comparison table to select a territory.',
            compareAreas: 'Compare territories',
            filterAreas: 'Filter territories',
            areasShown: 'Areas shown: {{count}}',
            tableNoResults: 'No territories match this search.',
            downloadCsv: 'Download CSV',
            csvPrepared: 'CSV prepared for {{count}} territories.',
            selectArea: 'Open territory',
            currentArea: 'Selected territory',
            sortAscending: 'Sorted ascending',
            sortDescending: 'Sorted descending',
            interpret: 'How to interpret the results',
            methodology: 'Methodology',
            dataRelease: 'Data and release',
            backDashboard: 'Back to dashboard',
            formula: 'Formula',
            aggregateTreatment: 'Aggregation',
            assumption: 'Key assumption',
            notMeasured: 'What is not measured',
            close: 'Close',
            unavailable: 'Unavailable',
            partial: 'Partial coverage',
            complete: 'Complete coverage',
            noEpisodesRange: 'A distinct episode total is unavailable for an arbitrary range because one episode may cross a month boundary.',
            multiYearContext: 'Education context is shown separately for each school year; learner counts are not summed across years.',
            contextCaveat: 'Education figures describe the school network and are not observed presence during alarms.',
            modality2022: 'For 2022/23, in-person learners are derived as total learners minus remote learners because a more detailed classification was not yet available.',
            modalityLater: 'Later years report in-person, remote and mixed modalities separately; “other modalities” is a derived residual that predominantly covers non-in-person modalities, including family-based and related arrangements.',
            mapAlternative: 'The same values and territory-selection controls are available in the comparison table.',
            methodQuestion: 'What does the dashboard estimate?',
            methodQuestionText: 'The dashboard estimates overlap between recorded air-alarm intervals and assumed school time. It does not observe actual timetables, attendance or lessons delivered.',
            sources: 'Sources and coverage',
            assumptions: 'Assumptions',
            processing: 'Alarm-interval processing',
            geography: 'Geographic allocation',
            indicators: 'Measures and formulas',
            weighting: 'Aggregation and ranges',
            education: 'Education context',
            missingness: 'Zero, partial coverage and unavailable values',
            limitations: 'Limitations and appropriate use',
            limitationsText: 'The dashboard does not measure learning loss, lessons actually cancelled, attendance, actual time in shelters, real school timetables, homework disruption, sleep disruption or individual learner exposure.',
            workedExample: 'Worked example',
            releaseInfo: 'Release information',
            architecture: 'Publication architecture',
            loading: 'Loading data…',
            fatal: 'The dashboard data could not be loaded.',
            fatalHelp: 'Refresh the page or try again later.',
            releaseMismatch: 'Release metadata are inconsistent.',
            invalidParams: 'Some invalid link parameters were replaced with safe values.',
            searchNoResults: 'No results found',
            area: 'Territory',
            share: 'Time share',
            days: 'Day share',
            precision: 'Geographic precision',
            coverage: 'Coverage',
            averageLocation: 'Average per active school location.',
            directResult: 'Result calculated directly for the hromada.',
            aggregateMetricContext: 'For national and oblast views, absolute values are averages per active school location; shares use the corresponding weighted numerators and denominators.',
            loadingArea: 'Loading data for the selected oblast…',
            loadAreaFailed: 'Data for the selected oblast could not be loaded. Try again.',
            geometryUnavailable: 'No controlled geometry is available for the selected hromada; analytical results and table selection remain available.',
            analyticalUnavailable: 'The analytical result is unavailable for this area and period; zero has not been substituted.',
            noData: 'No data row is available for the selected area and period.',
            sourcePrecisionMixed: 'Mixed geographic precision',
            sourcePrecisionNotApplicable: 'Not applicable',
            sourcePrecisionOblast: 'Allocated from oblast level',
            sourcePrecisionRaion: 'Allocated from raion level',
            alarmMeaning: 'The duration of unioned alarm intervals that overlap the assumed school operating window.',
            alarmFormula: 'overlap seconds ÷ 3,600; share = overlap seconds ÷ available assumed school seconds × 100',
            alarmAssumption: 'Monday–Friday, configured vacations, 08:00–15:00 in Europe/Kyiv.',
            alarmNot: 'Lessons actually cancelled, attendance or learning loss.',
            daysMeaning: 'A day is counted when an alarm has any positive overlap with assumed school time.',
            daysFormula: 'days with positive overlap ÷ available assumed school days × 100',
            daysAssumption: 'Only available assumed school days enter the denominator.',
            daysNot: 'Whether teaching stopped for the whole day.',
            episodesMeaning: 'Distinct processed alarm episodes with positive overlap within the school day.',
            episodesFormula: 'count of distinct processed episode identifiers with positive overlap',
            episodesAssumption: 'A long episode crossing day boundaries is counted once.',
            episodesNot: 'A sum of monthly episode counts for an arbitrary multi-month range.'
        }
    }
};
